/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kavita
 */
public class AbnormalPanel extends javax.swing.JPanel {

    private VitalSignHistory vsh;
    private double  maxBP, minBP;
    /**
     * Creates new form AbnormalPanel
     */
    public AbnormalPanel(VitalSignHistory vsh, double maxBP, double minBP) {
        this.vsh=vsh;
        this.maxBP = maxBP;
        this.minBP = minBP;
        
        initComponents();
        populateTable();
        
    }
    
    private void populateTable(){
    
    DefaultTableModel dtm = (DefaultTableModel) tblVitalSigns.getModel();
    dtm.setRowCount(0);
    for(VitalSigns vs : vsh.getAbnormalList(maxBP, minBP)){
        Object row[] = new Object [2];
        row[0] = vs;
        row[1] = vs.getBloodPressure();
        dtm.addRow(row);
        
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pulse = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSigns = new javax.swing.JTable();
        temperature = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        temTextField = new javax.swing.JTextField();
        bldPressure = new javax.swing.JLabel();
        pulseTextField = new javax.swing.JTextField();
        bldPTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Abnormal Vital Signs");

        pulse.setForeground(new java.awt.Color(0, 51, 153));
        pulse.setText("Pulse");

        deleteBtn.setForeground(new java.awt.Color(0, 0, 102));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        viewDetailsBtn.setForeground(new java.awt.Color(0, 0, 102));
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        tblVitalSigns.setForeground(new java.awt.Color(0, 51, 153));
        tblVitalSigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVitalSigns);

        temperature.setForeground(new java.awt.Color(0, 51, 153));
        temperature.setText("Temperature");

        date.setForeground(new java.awt.Color(0, 51, 153));
        date.setText("Date");

        dateTextField.setForeground(new java.awt.Color(0, 51, 153));
        dateTextField.setEnabled(false);
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        temTextField.setForeground(new java.awt.Color(0, 51, 153));
        temTextField.setEnabled(false);

        bldPressure.setForeground(new java.awt.Color(0, 51, 153));
        bldPressure.setText("Blood Pressure");

        pulseTextField.setForeground(new java.awt.Color(0, 51, 153));
        pulseTextField.setEnabled(false);
        pulseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseTextFieldActionPerformed(evt);
            }
        });

        bldPTextField.setForeground(new java.awt.Color(0, 51, 153));
        bldPTextField.setEnabled(false);
        bldPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldPTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(temperature)
                                            .addComponent(bldPressure)
                                            .addComponent(pulse)
                                            .addComponent(date))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(temTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bldPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(viewDetailsBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteBtn)))
                                .addGap(15, 15, 15))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDetailsBtn)
                    .addComponent(deleteBtn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperature)
                    .addComponent(temTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldPressure)
                    .addComponent(bldPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulse)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        int selectedrow = tblVitalSigns.getSelectedRow();
        if (selectedrow>=0)
        {

            VitalSigns vs = (VitalSigns) tblVitalSigns.getValueAt(selectedrow, 0);
            vsh.deleteVitals(vs);
            JOptionPane.showMessageDialog(null,"Vital Sign has been deleted");
            populateTable();

        }
    }//GEN-LAST:event_deleteBtnActionPerformed

        
        
    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        int selectedrow = tblVitalSigns.getSelectedRow();
        if (selectedrow>=0)
        {
            // t retrive the value from the selected row and display that in text field
            VitalSigns vs = (VitalSigns) tblVitalSigns.getValueAt(selectedrow, 0);
            bldPTextField.setText(String.valueOf(vs.getBloodPressure()));
            temTextField.setText(String.valueOf(vs.getTemperature()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(vs.getDate());
            
            
        }
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void pulseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulseTextFieldActionPerformed

    private void bldPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldPTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bldPTextField;
    private javax.swing.JLabel bldPressure;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pulse;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JTable tblVitalSigns;
    private javax.swing.JTextField temTextField;
    private javax.swing.JLabel temperature;
    private javax.swing.JButton viewDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
