/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavita
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    // creating a private variable
    private VitalSignHistory vsh;

    // a argumented constructor
    CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh; // assigning global varible with local variable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createVitalSigns = new javax.swing.JLabel();
        temperature = new javax.swing.JLabel();
        temTextField = new javax.swing.JTextField();
        bldPressure = new javax.swing.JLabel();
        bldPTextField = new javax.swing.JTextField();
        pulse = new javax.swing.JLabel();
        pulseTextField = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        createVitalSigns.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        createVitalSigns.setForeground(new java.awt.Color(204, 0, 51));
        createVitalSigns.setText("Create Vital Signs");

        temperature.setForeground(new java.awt.Color(0, 51, 153));
        temperature.setText("Temperature");

        temTextField.setForeground(new java.awt.Color(0, 51, 153));
        temTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                temTextFieldKeyReleased(evt);
            }
        });

        bldPressure.setForeground(new java.awt.Color(0, 51, 153));
        bldPressure.setText("Blood Pressure");

        bldPTextField.setForeground(new java.awt.Color(0, 51, 153));
        bldPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldPTextFieldActionPerformed(evt);
            }
        });
        bldPTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bldPTextFieldKeyReleased(evt);
            }
        });

        pulse.setForeground(new java.awt.Color(0, 51, 153));
        pulse.setText("Pulse");

        pulseTextField.setForeground(new java.awt.Color(0, 51, 153));
        pulseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseTextFieldActionPerformed(evt);
            }
        });
        pulseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pulseTextFieldKeyReleased(evt);
            }
        });

        date.setForeground(new java.awt.Color(0, 51, 153));
        date.setText("Date");

        dateTextField.setForeground(new java.awt.Color(0, 51, 153));
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });
        dateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateTextFieldKeyReleased(evt);
            }
        });

        saveBtn.setForeground(new java.awt.Color(0, 0, 102));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temperature)
                            .addComponent(bldPressure)
                            .addComponent(pulse)
                            .addComponent(date))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bldPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(createVitalSigns)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(createVitalSigns)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperature)
                    .addComponent(temTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldPressure)
                    .addComponent(bldPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulse)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(saveBtn)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bldPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldPTextFieldActionPerformed

    private void pulseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulseTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // to read the input from text field and save it into the local variable, we are creating local variable
        double temperature = Double.parseDouble(temTextField.getText());
        double bloodPressure = Double.parseDouble(bldPTextField.getText());
        int pulse = Integer.parseInt(pulseTextField.getText());
        String date = dateTextField.getText();
        VitalSigns v = vsh.addVitals();
        // we need to set the attributes using setter methods
        v.setTemperature(temperature);
        v.setBloodPressure(bloodPressure);
        v.setPulse(pulse);
        v.setDate(date);

        JOptionPane.showMessageDialog(null, "Vital Signs Added Sucessfully");

        temTextField.setText("");
        bldPTextField.setText("");
        pulseTextField.setText("");
        dateTextField.setText("");


    }//GEN-LAST:event_saveBtnActionPerformed

    private void temTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temTextFieldKeyReleased
        // TODO add your handling code here:
        try {
            double x = Double.parseDouble(temTextField.getText());
        } catch (NumberFormatException nfe) {
            temTextField.setText("");
        }
    }//GEN-LAST:event_temTextFieldKeyReleased

    private void bldPTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bldPTextFieldKeyReleased
        // TODO add your handling code here:
         try {
            double x = Double.parseDouble(bldPTextField.getText());
        } catch (NumberFormatException nfe) {
            bldPTextField.setText("");
        }
    }//GEN-LAST:event_bldPTextFieldKeyReleased

    private void pulseTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pulseTextFieldKeyReleased
        // TODO add your handling code here:
         try {
            int x = Integer.parseInt(pulseTextField.getText());
        } catch (NumberFormatException nfe) {
            pulseTextField.setText("");
        }
    }//GEN-LAST:event_pulseTextFieldKeyReleased

    private void dateTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTextFieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bldPTextField;
    private javax.swing.JLabel bldPressure;
    private javax.swing.JLabel createVitalSigns;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel pulse;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField temTextField;
    private javax.swing.JLabel temperature;
    // End of variables declaration//GEN-END:variables
}
